### ISSUE TITLE
💡 [REQUEST] - Add image modal popup for project thumbnail image in project page

### ISSUE THREAD

**Issue by sajald77** [geyserfund/geyser-app#1214]
### Summary

Add the feature to view the thumbnail image as larger image as a modal popup. 

Replace the _large.webp postfix for the thumbnail URL to _medium.webp, and use the _large.webp for the larger image in the modal.

### Basic Example

Clicking on the profile image will pop up a larger image in a modal for viewing purpose.

<img width="621" alt="Screenshot 2023-11-19 at 10 45 45 PM" src="https://github.com/geyserfund/geyser-app/assets/26449299/bc927890-2261-4832-85b7-c4cd2f69318a">

**Comment by avelynhc** [comment]
Hello, can I work on this issue? Thanks!

**Comment by sajald77** [comment]
> @sajald77 Hello, can I work on this issue? Thanks!

Absolutely, feel free to connect with us in Discord, if you need any help. You can simply work on it and create a PR mentioning this issue.
