### ISSUE TITLE
🐛 [BUG] - Cannot scroll through badges section

### ISSUE THREAD

**Issue by sajald77** [geyserfund/geyser-app#1215]
### Description

On the Geyser User Profile page. The badges section is not scrollable. So more than 4 badges are only partially seen or not seen at all. There is an issue with the layout.

The same issue is seen with the projects tab in the profile view. Here it is scrollable but the border is cut off like the badges section.

### Reproduction URL

geyser.fund/project/geyser

### Reproduction steps

```bash
go to a user profile
```

### Screenshots

![image](https://github.com/geyserfund/geyser-app/assets/26449299/b8911852-bdb9-4469-842c-7dfffc4f14aa)

### Version of Browser

chrome

### Operating system

mac

**Comment by sepehr-safari** [comment]
it seems fetching badges flow is totally broken somehow, no badges are shown on profile pages:

![image](https://github.com/geyserfund/geyser-app/assets/25853688/41958479-1cbc-4b18-86e5-215ac3f18881)

I've checked the flow. seems that it's trying to fetch badges from their nostr profiles which are vacant somehow. but at the same time there are some badges available from graphql query. I'm new to this, why is there 2 different data resources with different states?

**Comment by sajald77** [comment]
> it seems fetching badges flow is totally broken somehow, no badges are shown on profile pages:
> 
> ![image](https://private-user-images.githubusercontent.com/25853688/296778053-41958479-1cbc-4b18-86e5-215ac3f18881.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjg0MDUsIm5iZiI6MTcwNTMyODEwNSwicGF0aCI6Ii8yNTg1MzY4OC8yOTY3NzgwNTMtNDE5NTg0NzktMWNiYy00YjE4LTg2ZTUtMjE1YWMzZjE4ODgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDE0MTUwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4M2NlMmViNzk3ZTIzNGMwZGE3Mzk2Yzc3NDhkZTA5YWM4MzU3ZTliYTJjZDYwYjJlMDc3NGEzMTkxY2M1ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xUGR8-YuE0KE2_uZj0B8mc4ovQVg1XNs4gG1x2ZugQs)
> 
> I've checked the flow. seems that it's trying to fetch badges from their nostr profiles which are vacant somehow. but at the same time there are some badges available from graphql query. I'm new to this, why is there 2 different data resources with different states?

Yes there are two different sources for badges because of a couple of reasons:

- We have the awarding badge flow, in the backend that adds the badge to a user in the geyser db as well as publishes the event to Nostr ( when a badge is to be awarded, usually triggered after a funding action), but surprisingly the awarding badges in nostr fails more often than expected. As a fail safe for this, we show unawarded badges from geyer-db and awarded badge from Nostr. 
- When user clicks claim on the unawarded badge, it get's awarded and claimed in a single click, while an already awarded badge is only claimed.

And true, the badges flow does need some more love and better Nostr integration. We do have a plan for working on it, it's just there are more important stuff to build right now.
