### ISSUE TITLE
💡 [REQUEST] - <MILESTONES>

### ISSUE THREAD

**Issue by turizspace** [geyserfund/geyser-app#1417]
### Summary

![Screenshot 2024-04-19 185811](https://github.com/geyserfund/geyser-app/assets/143194249/24c6217c-13e6-4b78-8b45-9f910d1cfb8b)

### Basic Example

MILESTONES NEED TO BE DISPLAYED A BIT DIFFERENT IMO .  THERE IS NO WAS TO TELL USER THE SPECIFIC AMOUT FOR SPECIFIC MILESTONES. INSTEAD IT LOOS AS THOUGH EACH MILESTONE REQUIRES MORE FUNDING

**Comment by steliosrammos** [comment]
Hi @turizspace, thank you for opening this issue. We are working on this and have it in our internal tracking tool!
