### ISSUE TITLE
🐛 [BUG] - Nostr project search failed

### ISSUE THREAD

**Issue by SilberWitch** [geyserfund/geyser-app#1554]
### Description

I wanted to see what Nostr products are listed, so I clicked on the search and it returned an error, instead of a list of results.

### Reproduction URL

https://geyser.fund/?tagIds=2&sort=recent

### Reproduction steps

```bash
1. Go to the Geyser start page.
2. Click on 'see all' to the right of the words 'Trending in nostr'.
3. See error "Failed to fetch data".
```

### Screenshots

```bash
![Error message](https://i.nostr.build/POg37.png)
```

### Version of Browser

Kiwi Browser 124.0.6327.2

### Operating system

Android 11

**Comment by sajald77** [comment]
@SilberWitch thanks for reporting this one. This is fixed now.
