### ISSUE TITLE
🐛 [BUG] - wrong number included in statistic on My Projects splashpage

### ISSUE THREAD

**Issue by SilberWitch** [geyserfund/geyser-app#1616]
### Description

The splash page shows that we have received only 2,132 sats, but we have received 554,917 sats (as is correctly displayed one click later).

### Reproduction URL

[Geyser Fund - Crowdfunding with Bitcoin](https://geyser.fund/my-projects)

### Reproduction steps

```bash
1. Open https://geyser.fund/
2. Click on profile pic
3. Select "My Projects"
4. See error
```

### Screenshots

```bash
![Error on page](https://i.nostr.build/g6bViALAdXzoQHhk.png)
```

### Logs

*No response*

### Version of Browser

Firefox 115.14.0esr

### Operating system

Debian 12 Bookworm

**Comment by steliosrammos** [comment]
The "My Projects" view "Contribution Received" shows the total contributions your project has received over the last 7 days, not the total.

**Comment by SilberWitch** [comment]
Okay. That isn't made clear by the interface.

**Comment by steliosrammos** [comment]
You're right, we're going to improve that. Thank you for the feedback!
